"""Item removal and record

Revision ID: a743a54a0128
Revises: d4867f3a4c0a
Create Date: 2023-10-08 16:09:15.710134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a743a54a0128'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('type', postgresql.ENUM('iron', 'silicon', 'aluminum', 'calcium', name='materialtype'), nullable=False),
    sa.Column('min_amount', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_created'), 'record', ['created'], unique=False)
    op.create_index(op.f('ix_record_id'), 'record', ['id'], unique=False)
    op.create_index(op.f('ix_record_max_amount'), 'record', ['max_amount'], unique=False)
    op.create_index(op.f('ix_record_min_amount'), 'record', ['min_amount'], unique=False)
    op.create_index(op.f('ix_record_type'), 'record', ['type'], unique=False)
    op.create_index(op.f('ix_record_user_id'), 'record', ['user_id'], unique=False)
    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_item_id', table_name='item')
    op.drop_index('ix_item_title', table_name='item')
    op.drop_table('item')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    op.drop_index(op.f('ix_record_user_id'), table_name='record')
    op.drop_index(op.f('ix_record_type'), table_name='record')
    op.drop_index(op.f('ix_record_min_amount'), table_name='record')
    op.drop_index(op.f('ix_record_max_amount'), table_name='record')
    op.drop_index(op.f('ix_record_id'), table_name='record')
    op.drop_index(op.f('ix_record_created'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
